### ISSUE TITLE
Do you have an example, minimalist traffic.tar?

### ISSUE THREAD

**Issue by marklit** [alinmindroc/valhalla_traffic_poc#5]
Thanks for putting together this project.

I've been working my way through your code with the current master branch of Valhalla. There seems to be a chicken-and-egg problem with a valid ``traffic.tar`` file being in place. Do you have an example of a minimalist ``traffic.tar`` file? I believe it would get me past a few errors and get your code running on the master branch without issue.

I'm trying to avoid a dependency on any Docker if I can avoid it.

**Comment by alinmindroc** [comment]
Sure, here is the one generated by the docker image in this project:
[traffic.tar.zip](https://github.com/alinmindroc/valhalla_traffic_poc/files/9376518/traffic.tar.zip)

Unfortunately due to rapid changes in the Valhalla master branch I can't keep this repo up to date, but it still points to an older version of the code, and the docker image still builds correctly. Do you have any issue with?

**Comment by marklit** [comment]
Fantastic, thanks for that.

I got everything up until ``way_edges.txt`` working. From there I was able to generate an padestrian isochrone which is more than I thought I'd have done in a day.
